[package]
name = "discord_rpc"
version = "0.1.0"
authors = ["trimill"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-rpc-client = "0.3"
yaml-rust = "0.4"
